# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('opening_balance', models.FloatField(blank=True, null=True)),
                ('closing_balance', models.FloatField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=300)),
                ('balance_change', models.FloatField()),
                ('total_after_change', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
