# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='balance_change',
            field=models.FloatField(default=0.0),
        ),
    ]
