# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180924_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('item_type', models.CharField(choices=[('PZ', 'بيتزا'), ('MC', 'مكرونات'), ('SW', 'حلو'), ('SO', 'حادق')], max_length=2)),
                ('medium_price', models.FloatField()),
                ('large_price', models.FloatField()),
                ('components', models.TextField()),
            ],
        ),
    ]
