# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-25 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
