# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('IN', 'صالة'), ('DL', 'ديليفرى'), ('TA', 'تيك أواى')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
