# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180926_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
