# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180926_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
