# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180926_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
